language: php
php:
  - "5.6"
  - "5.5"
  - "5.4"

before_script:
  - composer self-update
  - composer install
  - chmod -r 777 /tests

script:
    - vendor/bin/phpunit -c phpunit.xml.dist
