language: php
php:
  - "5.6"
  - "5.5"
  - "5.4"

before_script:
  - composer self-update
  - composer install
  - sh -c "chmod -R 777 tests"
  - sh -c "chmod -R 777 src"
  - sh -c "ls -l"

script:
  - vendor/bin/phpunit -c phpunit.xml.dist